name: Cross-compile Rust
on:
  push:
    branches:
      - cargo-zig
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  CARGO_ZIGBUILD_VERSION: "0.22.1"
  PROTOC_HOME: "compilation-tools/protoc"
  PROTOC_VERSION: "34.1"
  # TODO: Stupid name
  PBS_AARCH_HOME: "/tmp/pbs-linux-aarch64"
  # TODO: Organize to only use a single version - since we can't use env in env
  PBS_VERSION: "20260325"
  PBS_VERSION_FULL: "3.14.3+20260325"
  PYTHON_MAJOR_MINOR: "3.14"
  ZIG_HOME: "compilation-tools/zig"
  ZIG_VERSION: "0.15.2"

jobs:
  setup-deps:
    name: Setup dependencies
    runs-on: ubuntu-latest

    steps:
      # ================================
      # zig
      # ================================
      - name: Cache Zig
        id: cache-zig
        uses: actions/cache@v5
        with:
          path: ${{ env.ZIG_HOME }}
          key: cache-zig-${{ runner.os }}-${{ env.ZIG_VERSION }}

      - name: Setup Zig
        if: steps.cache-zig.outputs.cache-hit != 'true'
        run: |
          set -euo pipefail
          mkdir -p "${{ env.ZIG_HOME }}"
          ZIG_ARCHIVE="zig-x86_64-linux-${{ env.ZIG_VERSION }}.tar.xz"
          curl -v -L "https://ziglang.org/download/${{ env.ZIG_VERSION }}/$ZIG_ARCHIVE" -o "/tmp/$ZIG_ARCHIVE"
          tar xf "/tmp/$ZIG_ARCHIVE" --directory "${{ env.ZIG_HOME }}" --strip-components=1

      # ================================
      # cargo-zigbuild
      # ================================
      # TODO: This will be under the rust-cache
      - name: Cache cargo-zigbuild
        id: cache-cargo-zigbuild
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/cargo-zigbuild
          key: cache-cargo-zigbuild-${{ runner.os }}-${{ env.CARGO_ZIGBUILD_VERSION }}

      - name: Setup cargo-zigbuild
        if: steps.cache-cargo-zigbuild.outputs.cache-hit != 'true'
        run: cargo install --locked cargo-zigbuild --version ${{ env.CARGO_ZIGBUILD_VERSION }}

      # ================================
      # protoc
      # ================================
      - name: Cache protoc
        id: cache-protoc
        uses: actions/cache@v5
        with:
          path: ${{ env.PROTOC_HOME }}
          key: cache-protoc-${{ runner.os }}-${{ env.PROTOC_VERSION }}

      - name: Setup protoc
        if: steps.cache-protoc.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p "${{ env.PROTOC_HOME }}"
          PROTOC_ZIP="protoc-${{ env.PROTOC_VERSION }}-linux-x86_64.zip"
          gh release download v${{ env.PROTOC_VERSION }} --repo protocolbuffers/protobuf --pattern $PROTOC_ZIP --dir /tmp/
          unzip /tmp/$PROTOC_ZIP -d "${{ env.PROTOC_HOME }}"


      # ================================
      # PBS
      # ================================
      # TODO: Handle this per-arch?
      - name: Cache PBS aarch64
        id: cache-pbs-aarch
        uses: actions/cache@v5
        with:
          path: ${{ env.PBS_AARCH_HOME }}
          key: cache-pbs-aarch-${{ runner.os }}-${{ env.PYTHON_AARCH_VERSION }}

      - name: Setup aarch64 Python
        if: steps.cache-pbs-aarch.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p "${{ env.PBS_AARCH_HOME }}"
          PBS_ARCHIVE="cpython-${{ env.PBS_VERSION_FULL }}-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz"
          gh release download ${{ env.PBS_VERSION }} --repo astral-sh/python-build-standalone --pattern $PBS_ARCHIVE --dir /tmp/
          tar xf "/tmp/$PBS_ARCHIVE" --directory "${{ env.PBS_AARCH_HOME }}" --strip-components=1
          
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: setup-deps
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
    
    steps:
      - uses: actions/checkout@v6

      # ================================
      # Restore Caches
      # ================================
      - name: Restore Zig
        uses: actions/cache/restore@v5
        id: restore-zig
        with:
          path: ${{ env.ZIG_HOME }}
          key: cache-zig-${{ runner.os }}-${{ env.ZIG_VERSION }}

      - name: Check zig
        if: steps.restore-zig.outputs.cache-hit != 'true'
        run: exit 1

      - name: Restore cargo-zigbuild cache
        uses: actions/cache/restore@v5
        id: restore-cargo-zigbuild
        with:
          path: ~/.cargo/bin/cargo-zigbuild
          key: cache-cargo-zigbuild-${{ runner.os }}-${{ env.CARGO_ZIGBUILD_VERSION }}

      - name: Check cargo-zigbuild
        if: steps.restore-cargo-zigbuild.outputs.cache-hit != 'true'
        run: exit 1

      - name: Restore protoc
        id: restore-protoc
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.PROTOC_HOME }}
          key: cache-protoc-${{ runner.os }}-${{ env.PROTOC_VERSION }}
      
      - name: Check protoc
        if: steps.restore-protoc.outputs.cache-hit != 'true'
        run: exit 1

      # TODO: This is per-arch
      - name: Restore PBS aarch64
        id: restore-pbs-aarch
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.PBS_AARCH_HOME }}
          key: cache-pbs-aarch-${{ runner.os }}-${{ env.PYTHON_AARCH_VERSION }}
    
      - name: Check pbs
        if: steps.restore-pbs-aarch.outputs.cache-hit != 'true'
        run: exit 1

      # ================================
      # Build
      # ================================

      - name: Setup PATHs
        run: |
          echo "${{ env.PROTOC_HOME }}/bin" >> $GITHUB_PATH
          echo "${{ env.ZIG_HOME }}" >> $GITHUB_PATH
          echo "${{ env.PYTHON_AARCH_HOME }}/bin" >> $GITHUB_PATH

          echo "::notice::PATH=$PATH"
          echo "::notice::GITHUB_PATH=$GITHUB_PATH"
          
          # TODO: There is no zig
          echo "::notice::zig=$(zig --version)"
          echo "::notice::cargo-zig=$(cargo-zigbuild --version)"
          echo "::notice::protoc=$(protoc --version)"

      - name: Try compiling
        env:
          AWS_LC_SYS_NO_JITTER_ENTROPY: "1"
          PYO3_CROSS_PYTHON_VERSION: "3.14"
          RUSTFLAGS: "-L ${{ env.PBS_AARCH_HOME }}/lib"
        run: |
          echo "::notice::PATH=$PATH"

          # TODO: Should this be part of the central cache?
          rustup target add ${{ matrix.target }}

          cargo zigbuild --manifest-path ./src/rust/Cargo.toml --release --target ${{ matrix.target }}
          echo "::notice::$(ls -la)"
          echo "::notice::$(ls -la ./src/rust/target)"
          echo "::notice::$(ls -la ./src/rust/target/release)"
          echo "::notice::$(ls -la ./src/rust/target/${{ matrix.target }})"